### ISSUE TITLE
Cleanup .module file

### ISSUE THREAD

**Issue by jodyHamilton** [zivtech/require-to-publish#10]
https://github.com/zivtech/require-to-publish/blob/master/required_for_pub.module refer here for line numbers

"Implements of hook_help()." should not say 'of' line 4

Indenting bad on line 20

Line 27 should not take a $form_id parameter as form_id is specified by the function name

Missing period in comments line 56 and 94

Line 113, exiting if not a node should be at the start of that function. Line 109, checking if entity type is field collection should be removed. and line 118 which is rechecking the same thing. and line 161.

Extra spaces are on line 135

Extra line on line 146

bad indenting line 169

missing t() on line 173

remove line 176

182 should refer to nodes as this only works on nodes. related this field setting should only show for node fields.

on line 185, not sure what they're doing with those options in drupal_add_css. may not be necessary. had that earlier in the file too.

validate function starting line 184 is too long and too nested to be easy to parse. should be split up into easier to understand subfunctions.

fix comment typo/spacing on line 256

fix typo on line 259

extra line 262, 268, 273, 275

typo line 287

these guys should really try code review :)

fix indenting and extra lines on 294-307

extra line 311

missing space after foreach line 312

extra lines 317, 319, 321

**Comment by dzink** [comment]
https://github.com/zivtech/require-to-publish/pull/13
